name: My first workflow

on: push

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPO
        uses: actions/checkout@v6
        
      - name: welcome message
        run: echo "hi from github actions"

      - name: listfiles
        run: ls

      - name: Read file
        run: cat README.md