name: My first workflow

on: push

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPO
        uses: actions/checkout@v6
        
      - name: list and read files
        run: |
          echo "hi from github actions"
          ls -lrta
          cat README.md